apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: canary-demo
  template:
    metadata:
      labels:
        app: canary-demo
    spec:
      containers:
      - name: web
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
strategy:
  stableService: canary-active-svc
  canaryService: canary-preview-svc
  steps:
      - setWeight: 25
      - pause: { duration: 15s }
      - setWeight: 50
      - pause: { duration: 15s }
      - setWeight: 75
      - pause: { duration: 15s }

